# Custom markdownlint rules
default: true

# Allow longer line length
MD013:
  line_length: 200
  tables: false
  code_blocks: false

# Allow multiple top-level headings
MD025: false

# Allow HTML in markdown
MD033: false

# Allow inconsistent heading hierarchy
MD001: false

# Allow duplicate headings
MD024: false
