# GoFile Downloader Configuration

# Web server settings
port: 2355
host: "0.0.0.0"
debug: false
secret_key: "change-this-in-production"  # Flask secret key

# Download settings
base_dir: "/app"  # Base directory for downloads
default_retries: 3  # Default retry attempts for failed downloads
retry_delay: 5  # Seconds to wait between retries
default_throttle: null  # Default throttle in KB/s (null for unlimited)

# UI settings
results_per_page: 20
dashboard_refresh_rate: 3000  # Milliseconds between auto-refresh
task_expiry: 604800  # Seconds after which completed tasks are auto-removed (7 days)

# Logging
log_level: "INFO"
log_format: "[%(asctime)s][%(funcName)20s()][%(levelname)-8s]: %(message)s"
